const DUMMY_ORDER = {
  id: 6489,
  parent_id: 0,
  status: "pending",
  currency: "EUR",
  version: "6.4.1",
  prices_include_tax: false,
  date_created: "2022-05-16T08:21:18", //
  date_modified: "2022-05-16T08:26:30", //
  discount_total: "0.00",
  discount_tax: "0.00",
  shipping_total: "0.00",
  shipping_tax: "0.00",
  cart_tax: "0.00",
  total: "101.05", //
  total_tax: "0.00",
  customer_id: 0,
  order_key: "wc_order_Jvr8s9xNUbMYj",
  billing: {
    first_name: "",
    last_name: "",
    company: "",
    address_1: "",
    address_2: "",
    city: "",
    state: "",
    postcode: "",
    country: "FR",
    email: "",
    phone: "",
  },
  shipping: {
    first_name: "Prénom",
    last_name: "nom",
    company: "Entreprise",
    address_1: "Adresse ligne 1",
    address_2: "Adresse ligne 2",
    city: "Lyon",
    state: "Rhône",
    postcode: "69001",
    country: "FR",
    phone: "XX XX XX XX",
  },
  payment_method: "",
  payment_method_title: "",
  transaction_id: "",
  customer_ip_address: "",
  customer_user_agent: "",
  created_via: "admin",
  customer_note: "notes",
  date_completed: null,
  date_paid: null,
  cart_hash: "",
  number: "63",
  meta_data: [],
  line_items: [
    {
      id: 1,
      name: "WordPress Pennant",
      product_id: 38,
      variation_id: 0,
      quantity: 1,
      tax_class: "",
      subtotal: "11.05",
      subtotal_tax: "0.00",
      total: "11.05",
      total_tax: "0.00",
      taxes: [],
      meta_data: [],
      sku: "wp-pennant",
      price: 11.05,
      parent_name: null,
    },
    {
      id: 2,
      name: "Hoodie with Logo",
      product_id: 17,
      variation_id: 0,
      quantity: 2,
      tax_class: "",
      subtotal: "90.00",
      subtotal_tax: "0.00",
      total: "90.00",
      total_tax: "0.00",
      taxes: [],
      meta_data: [],
      sku: "woo-hoodie-with-logo",
      price: 45,
      parent_name: null,
    },
  ],
  tax_lines: [],
  shipping_lines: [],
  fee_lines: [],
  coupon_lines: [],
  refunds: [],
  payment_url:
    "http://localhost/wp593/commander/order-pay/63/?pay_for_order=true&key=wc_order_Jvr8s9xNUbMYj",
  date_created_gmt: "2022-05-16T06:21:18",
  date_modified_gmt: "2022-05-16T06:26:30",
  date_completed_gmt: null,
  date_paid_gmt: null,
  currency_symbol: "€",
  _links: {
    self: [{ href: "http://localhost/wp593/wp-json/wc/v3/orders/63" }],
    collection: [{ href: "http://localhost/wp593/wp-json/wc/v3/orders" }],
  },
};

export default DUMMY_ORDER;
